config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :users, only: [:show]
  get '/my_profile', to: 'users#my_profile', as: 'my_profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :trees do
    resources :adoptions, except: [:new, :destroy]
  end

  resources :adoptions, only: [:destroy]

  resources :adoptions, only: [] do
    resources :reviews, only: [:create]
  end
end

app/models/adoption.rb
class Adoption < ApplicationRecord
  belongs_to :tree
  belongs_to :user

  has_one :review, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :adoption

  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/models/tree.rb
class Tree < ApplicationRecord
  belongs_to :user
  has_many :adoptions, dependent: :destroy
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :fruit, inclusion: { in: ["Apple",
                                      "Apricot",
                                      "Cherry",
                                      "Chestnut",
                                      "Coconut",
                                      "Fig",
                                      "Grapefruit",
                                      "Hazel",
                                      "Mandarin",
                                      "Mango",
                                      "Mirabellier",
                                      "Mulberry",
                                      "Olivier",
                                      "Orange",
                                      "Pear",
                                      "Plum"]
}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trees, dependent: :destroy
  has_many :adoptions, dependent: :destroy
end

app/controllers/adoptions_controller.rb
class AdoptionsController < ApplicationController
  def create
    @tree = Tree.find(params[:tree_id])
    @adoption = Adoption.new(adoption_params)
    @adoption.tree = @tree
    @adoption.user = current_user
    @adoption.starts_at = Time.now.to_date
    @adoption.ends_at = Time.now.to_date + 1.year
    @adoption.save

    redirect_to tree_path(@tree)
  end

  private

  def adoption_params
    params.require(:adoption).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    @adoption = Adoption.find(params[:adoption_id])
    @review.adoption = @adoption
    @review.user = current_user
    @review.save
    redirect_to my_profile_path
  end

  private

  def review_params
    params.require(:review).permit(:rating, :description)
  end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :set_tree, only: %i[edit update show]

  def index
    @trees = Tree.all
    if params[:query].present?
      @trees = Tree.all.where("address ILIKE ?", "%#{params[:query]}%")
      if @trees.count == 0
        @trees = Tree.all
        flash.alert = "no tree in #{params[:query]}.."
      end
    end

    @markers = @trees.geocoded.map do |tree|
      {
        lat: tree.latitude,
        lng: tree.longitude
      }
    end
  end

  def show
  end

  def new
    @tree = Tree.new
  end

  def create
    @user = current_user
    @tree = Tree.new(tree_params)
    @tree.user = @user
    if @tree.save
      redirect_to tree_path(@tree)
    else
      render :new
    end
  end

  def edit
    redirect_to tree_path(@tree) unless @tree.user == current_user
  end

  def update
    @tree.update(tree_params)
    redirect_to tree_path(@tree)
  end

  private

  def tree_params
    params.require(:tree).permit(:name,
                                 :address,
                                 :price,
                                 :quantity_per_year,
                                 :fruit,
                                 :description,
                                 :short_description,
                                 :photo)
  end

  def set_tree
    @tree = Tree.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @trees = @user.trees
  end

  def my_profile
    @user = current_user
    @trees = @user.trees
    @adoptions = @user.adoptions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuA - Adopte un arbre</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= favicon_link_tag asset_path('arbre.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <h1>Adopte un arbre</h1>
  <p>Vous recevrez les meilleurs fruits après chaque cueillette</p>
  <h2>Recherche un arbre autour de chez toi</h2>
  <%= form_tag trees_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Enter your city" %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>

  <%= link_to "Voir les arbres", trees_path %>
</div>

app/views/shared/_form.html.erb
<%= simple_form_for @tree do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :price %>
  <%= f.input :quantity_per_year %>
  <%= f.input :fruit %>
  <%= f.input :short_description %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/shared/_form_adoption.html.erb
<div class="card-adoption">
  <p> Adoptez le <%= @tree.name %> </p>
  <p>Prix : <%= @tree.price %>€ / an</p>
  <%= simple_form_for locales do |f| %>
    <%= f.input :name, label: "Nom" %>
    <%= f.button :submit, "Adopter", class: "btn-add" %>
  <% end %>
</div>

app/views/shared/_form_tree.html.erb
<%= simple_form_for @tree do |f| %>
  <%= f.input :name %>
  <%= f.input :address,
              input_html: { data: { geocoder_target: "address" }, class: 'd-none' },
              wrapper_html: { data: { controller: "geocoder",
                                      geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
  <%= f.input :price %>
  <%= f.input :quantity_per_year %>
  <%= f.input :fruit, collection: ["Apple",
                                   "Apricot",
                                   "Cherry",
                                   "Chestnut",
                                   "Coconut",
                                   "Fig",
                                   "Grapefruit",
                                   "Hazel",
                                   "Mandarin",
                                   "Mango",
                                   "Mirabellier",
                                   "Mulberry",
                                   "Olivier",
                                   "Orange",
                                   "Pear",
                                   "Plum"] %>
  <%= f.input :short_description %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag asset_path('arbre.png') %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add a tree", new_tree_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "All trees", trees_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/paulschauss", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", my_profile_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_new_review.html.erb
<%= simple_form_for locales do |f| %>
  <%= f.input :rating %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/trees/edit.html.erb
<div class="container">
  <%= render 'shared/form_tree' %>
</div>

app/views/trees/index.html.erb
<div class="container">
  <div style="width: 100%; height: 500px;"
       data-controller="mapbox"
       data-mapbox-api-key-value="<%= ENV["MAPBOX_API_KEY"] %>"
       data-mapbox-markers-value="<%= @markers.to_json %>"></div>
  <div class="btn-layout">
    <%= link_to "Retour", :back, class: "btn-ghost" %>
    <%= link_to "Ajouter un arbre", new_tree_path, class: "btn-add" %>
  </div>
  <div class="grid grid--3-cols grid--2-cols grid-margin-bottom">
      <% @trees.each do |tree| %>
        <%= link_to tree_path(tree) do %>
          <div class="card-tree"
               style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)),
                                        url('<%= cl_image_path tree.photo.key, height: 300, object_fit: :contain %>')">
            <h4 class="title"><%= tree.name %></h4>
            <p class= "price"><%= tree.price %>€ / par an</p>
          </div>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/trees/new.html.erb
<div class="container">
  <%= render 'shared/form_tree' %>
</div>

app/views/trees/show.html.erb
<div class="container">
  <div class="btn-layout">
    <%= link_to "Retour", :back, class: "btn-ghost" %>
    <% if @tree.user == current_user %>
      <%= link_to edit_tree_path(@tree) do %>
        <i class="icon-edit fa-solid fa-pen-to-square"></i>
      <% end %>
    <% end %>
  </div>

  <div class="show-tree-main">
    <h2><%= @tree.name %></h2>
    <% if @tree.photo.key %>
      <%= cl_image_tag @tree.photo.key, height: 300, width: 400, crop: :fill %>
    <% end %>
  </div>

  <div class="show-tree-body">
    <div class="show-tree-text">
      <p><%= @tree.description %></p>
      <p>📍 <%= @tree.address %></p>
    </div>

    <% unless current_user == @tree.user %>
      <%= render 'shared/form_adoption', locales: [ @tree, Adoption.new ]%>
    <% end %>
  </div>

  <div class="d-flex">
    <p> Producteur : </p>
    <%= link_to user_path(@tree.user) do %>
      <p><%= @tree.user.first_name %> <%= @tree.user.last_name %></p>
    <% end %>
  </div>

  <h4>Reviews</h4>

  <div class="reviews">
    <% @tree.adoptions.each do |adoption|%>
      <div class="review">

        <% if adoption.review %>
          <div class="d-flex">
            <p>Par : </p>
            <%= link_to user_path(adoption.review.user) do %>
              <p> <%= adoption.review.user.first_name %> <%= adoption.review.user.last_name %></p>
            <% end %>
          </div>
          <p><%= adoption.review.rating %> stars</p>
          <p><%= adoption.review.description %></p>
        <% else %>
          <p>l'arbre n'a pas de commentaire</p>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

app/views/users/my_profile.html.erb
<div class="container">
  <h1> Profil de
    <%= @user.first_name %>
    <%= @user.last_name %>
  </h1>

  <div>
    <h3>My trees :</h3>
    <% @trees.each do |tree| %>
      <%= link_to tree_path(tree) do %>
        <%= tree.name %>
      <% end %>
    <% end %>
  </div>

  <div>
    <h3>My adoptions :</h3>
    <% @adoptions.each do |adoption| %>

      <h4><%= adoption.name %> : <%= adoption.tree.fruit %> de <%= adoption.tree.name %></h4>
      <p>depuis : <%= adoption.starts_at %></p>
      <p>jusqu'a : <%= adoption.ends_at %></p>

      <% if adoption.review.nil? %>
        <p>Comment se passe ton adoption ?</p>
        <%= render 'shared/new_review', locales: [adoption, Review.new] %>
      <% end %>

      <% unless adoption.review.nil? %>
        <h5>Review : </h5>
        <p><%= adoption.review.rating %></p>
        <p><%= adoption.review.description %></p>
      <% end %>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1>
    <%= @user.first_name %>
    <%= @user.last_name %>
  </h1>

  <h3>Ses arbres :</h3>
  <% @trees.each do |tree| %>
    <p><%= tree.name %></p>

    <p>Review : </p>
    <% tree.adoptions.each do |adoption| %>
      <%= adoption.review.rating %>
      <%= adoption.review.description %>
    <% end %>

  <% end %>

</div>